- hosts: Ubuntu
  tasks:
    - name: Add Telegraf Repository
      shell:
        cmd: wget -qO- https://repos.influxdata.com/influxdb.key | sudo apt-key add -
        warn: false

    - name: Add Telegraf to apt-sources
      shell: echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
        
    - name: Add Telegraf Key
      apt_key:
        url: https://repos.influxdata.com/influxdb.key

    - name: Update Apt Cache
      apt: 
        update_cache: true
        force_apt_get: true